// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: packimports(3) 
// Source File Name:   RegistryFrame.java

package frames;

import classes.Message;
import classes.User;
import classes.usrclasses.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

// Referenced classes of package frames:
//            Window, MainFrame

public class RegistryFrame extends Window
    implements ActionListener
{

    public RegistryFrame(String title, MainFrame main)
    {
        super(title);
        initComponents();
        this.main = main;
        super.setLocationRelativeTo(null);
        cancelBtn.addActionListener(this);
        addBtn.addActionListener(this);
        message = new Message();
        buttonGroup1.add(sexFem);
        buttonGroup1.add(sexMale);
        sexFem.setSelected(true);
        super.setDefaultCloseOperation(0);
        super.setLocationRelativeTo(null);
        super.m.setMassage("\277Quieres cancelar el registro?");
    }

    public void actionPerformed(ActionEvent event)
    {
        if(event.getSource() == cancelBtn)
        {
            Message m = new Message(new Object[] {
                "S\355", "No"
            }, "Cancerla", "\277Quieres cancelar el registro?");
            if(m.showMessage() == 0)
                ownClose();
        } else
        if(event.getSource() == addBtn && verify())
            addUser();
    }

    private boolean verify()
    {
        boolean aux = true;
        if(nameTxt.getText().isEmpty() || yearsTxt.getText().isEmpty() || eMailTxt.getText().isEmpty() || phone0Txt.getText().isEmpty() || weigthTxt.getText().isEmpty() || waistSizeTxt.getText().isEmpty() || hipSizeTxt.getText().isEmpty() || heightTxt.getText().isEmpty() || actvPhysTxt.getText().isEmpty() || actvPhysDurationTxt.getText().isEmpty() || hungryHourTxt.getText().isEmpty() || palceEatTxt.getText().isEmpty() || whoFoodsTxt.getText().isEmpty() || watterTxt.getText().isEmpty())
        {
            message.showMessage();
            return false;
        }
        try
        {
            Float.parseFloat(weigthTxt.getText().toString());
            Float.parseFloat(heightTxt.getText().toString());
            Float.parseFloat(waistSizeTxt.getText().toString());
            Float.parseFloat(hipSizeTxt.getText().toString());
            Float.parseFloat(actvPhysDurationTxt.getText().toString());
            Float.parseFloat(watterTxt.getText().toString());
        }
        catch(Exception e)
        {
            message.showMessage(new Object[] {
                "Ok"
            }, "Datos incompatibles", "El peso, estatura y cintura deben ser datos num\351ricos.");
            return false;
        }
        return true;
    }

    public void ownClose()
    {
        super.setVisible(false);
        main.setVisible(true);
    }

    private void addUser()
    {
        char gen = sexFem.isSelected() ? 'f' : 'm';
        User user = new User();
        user.setPersonalData(new PersonalData(nameTxt.getText(), yearsTxt.getText(), eMailTxt.getText(), gen, phone0Txt.getText(), adressTxt.getText()));
        float weigth = Float.parseFloat(weigthTxt.getText().toString());
        float height = Float.parseFloat(heightTxt.getText().toString()) / 100F;
        user.setAnthropometricData(new AnthropometricData(weigth, height * 100F, Float.parseFloat(waistSizeTxt.getText().toString()), Float.parseFloat(hipSizeTxt.getText().toString()), weigth / (height * height), riskTxt.getText().toString(), dxTxt.getText().toString()));
        user.setMedicalRecord(new MedicalRecord(actualAilmentTxt.getText(), actualTreatmentTxt.getText(), surgeriesTxt.getText(), complementsTxt.getText()));
        user.setPhysicalActivity(new PhysicalActivity(actvPhysBox.getSelectedItem().toString(), actvPhysTxt.getText().toString(), (int)Float.parseFloat(actvPhysDurationTxt.getText().toString()), atcvPhysFrequenBox.getSelectedItem().toString()));
        boolean record[] = new boolean[12];
        boolean symptoms[] = new boolean[12];
        record[0] = sobrepeso_checkbox.getState();
        record[1] = obesidad_checkbox.getState();
        record[2] = cancer_checkbox.getState();
        record[3] = diabetes_checkbox.getState();
        record[4] = alcoholismo_checkbox.getState();
        record[5] = hiper_checkbox.getState();
        record[6] = cardiopatia_checkbox.getState();
        record[7] = dislipidemias_checkbox.getState();
        record[8] = enfhepaticas_checkbox.getState();
        record[9] = enfrespiratorias_checkbox.getState();
        record[10] = enfrenales_checkbox.getState();
        record[11] = otro_checkbox.getState();
        symptoms[0] = nauseas_checkbox.getState();
        symptoms[1] = vomito_checkbox.getState();
        symptoms[2] = diarrea_checkbox.getState();
        symptoms[3] = profmasticacion_checkbox.getState();
        symptoms[4] = glucion_checkbox.getState();
        symptoms[5] = estomacal_checkbox.getState();
        symptoms[6] = cansancio_checkbox.getState();
        symptoms[7] = estreF1imiento_checkbox.getState();
        symptoms[8] = gastritis_checkbox.getState();
        symptoms[9] = mareos_checkbox.getState();
        symptoms[10] = alteracion_checkbox.getState();
        symptoms[11] = indigestion_checkbox.getState();
        user.setHereditaryRecord(new HereditaryRecord(record, symptoms));
        user.setPersonalHabits(new PersonalHabits(Integer.parseInt(eatCountBox.getSelectedItem().toString()), Integer.parseInt(colationsBox.getSelectedItem().toString()), new String[] {
            habitsYesNoBox01.getSelectedItem().toString(), habitsYesNoBox01.getSelectedItem().toString(), habitsYesNoBox01.getSelectedItem().toString()
        }, drinkFrequentyBox.getSelectedItem().toString(), smokeFreqTxt.getSelectedItem().toString(), hungryHourTxt.getText().toString(), palceEatTxt.getText().toString(), whoFoodsTxt.getText().toString(), Integer.parseInt(watterTxt.getText().toString())));
        String type[] = new String[22];
        String perDay[] = new String[22];
        String perWeek[] = new String[22];
        String perMonth[] = new String[22];
        type[0] = yogurthType.getText();
        perDay[0] = yogurthDay.getText();
        perWeek[0] = yogurthWeek.getText();
        perMonth[0] = yogurthMonth.getText();
        type[1] = frutaType.getText();
        perDay[1] = frutaDay.getText();
        perWeek[1] = frutaWeek.getText();
        perMonth[1] = frutaMonth.getText();
        type[2] = verduraType.getText();
        perDay[2] = verduraDay.getText();
        perWeek[2] = verduraWeek.getText();
        perMonth[2] = verduraMonth.getText();
        type[3] = tortillaType.getText();
        perDay[3] = tortillaDay.getText();
        perWeek[3] = tortillaWeek.getText();
        perMonth[3] = tortillaMonth.getText();
        type[4] = panType.getText();
        perDay[4] = panDay.getText();
        perWeek[4] = panWeek.getText();
        perMonth[4] = panMonth.getText();
        type[5] = pastasType.getText();
        perDay[5] = pastasDay.getText();
        perWeek[5] = pastasWeek.getText();
        perMonth[5] = pastasMonth.getText();
        type[6] = arrozType.getText();
        perDay[6] = arrozDay.getText();
        perWeek[6] = arrozWeek.getText();
        perMonth[6] = arrozMonth.getText();
        type[7] = cerealType.getText();
        perDay[7] = cerealDay.getText();
        perWeek[7] = cerealWeek.getText();
        perMonth[7] = cerealMonth.getText();
        type[8] = carnesType.getText();
        perDay[8] = carnesDay.getText();
        perWeek[8] = carnesWeek.getText();
        perMonth[8] = carnesMonth.getText();
        type[9] = polloType.getText();
        perDay[9] = polloDay.getText();
        perWeek[9] = polloWeek.getText();
        perMonth[9] = polloMonth.getText();
        type[10] = huevosType.getText();
        perDay[10] = huevosDay.getText();
        perWeek[10] = huevosWeek.getText();
        perMonth[10] = huevosMonth.getText();
        type[11] = pescadoType.getText();
        perDay[11] = pescadoDay.getText();
        perWeek[11] = pescadoWeek.getText();
        perMonth[11] = pescadoMonth.getText();
        type[12] = jamonType.getText();
        perDay[12] = jamonDay.getText();
        perWeek[12] = jamonWeek.getText();
        perMonth[12] = jamonMonth.getText();
        type[13] = salchichaType.getText();
        perDay[13] = salchichaDay.getText();
        perWeek[13] = salchichaWeek.getText();
        perMonth[13] = salchichaMonth.getText();
        type[14] = quesoType.getText();
        perDay[14] = quesoDay.getText();
        perWeek[14] = quesoWeek.getText();
        perMonth[14] = quesoMonth.getText();
        type[15] = azucarType.getText();
        perDay[15] = azucarDay.getText();
        perWeek[15] = azucarWeek.getText();
        perMonth[15] = azucarMonth.getText();
        type[16] = grasasType.getText();
        perDay[16] = grasasDay.getText();
        perWeek[16] = grasasWeek.getText();
        perMonth[16] = grasasMonth.getText();
        type[17] = dulcesType.getText();
        perDay[17] = dulcesDay.getText();
        perWeek[17] = dulcesWeek.getText();
        perMonth[17] = dulcesMonth.getText();
        type[18] = papasType.getText();
        perDay[18] = papasDay.getText();
        perWeek[18] = papasWeek.getText();
        perMonth[18] = papasMonth.getText();
        type[19] = comidaType.getText();
        perDay[19] = comidaDay.getText();
        perWeek[19] = comidaWeek.getText();
        perMonth[19] = comidaMonth.getText();
        type[20] = refrescosType.getText();
        perDay[20] = refrescosDay.getText();
        perWeek[20] = refrescosWeek.getText();
        perMonth[20] = refrescosMonth.getText();
        type[21] = otrosType.getText();
        perDay[21] = otrosDay.getText();
        perWeek[21] = otrosWeek.getText();
        perMonth[21] = otrosMonth.getText();
        user.setDiet(new Diet(type, perDay, perWeek, perMonth));
        main.addItem(user);
        ownClose();
    }
    //Generado por nerbeans
    private void initComponents()
    {
        buttonGroup1 = new ButtonGroup();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        cancelBtn = new JButton();
        jTabbedPane1 = new JTabbedPane();
        jPanel1 = new JPanel();
        label1 = new Label();
        label2 = new Label();
        label3 = new Label();
        label4 = new Label();
        nameTxt = new TextField();
        yearsTxt = new TextField();
        eMailTxt = new TextField();
        label5 = new Label();
        phone0Txt = new TextField();
        sexFem = new JRadioButton();
        sexMale = new JRadioButton();
        label6 = new Label();
        adressTxt = new TextField();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jScrollPane5 = new JScrollPane();
        actualTreatmentTxt = new JTextArea();
        jScrollPane6 = new JScrollPane();
        actualAilmentTxt = new JTextArea();
        jScrollPane7 = new JScrollPane();
        complementsTxt = new JTextArea();
        jScrollPane8 = new JScrollPane();
        surgeriesTxt = new JTextArea();
        label_fisica = new JLabel();
        fisica = new JLabel();
        actvPhysBox = new JComboBox();
        atcvPhysFrequenBox = new JComboBox();
        cual_fisica = new JLabel();
        jScrollPane12 = new JScrollPane();
        actvPhysTxt = new JTextPane();
        duracion = new JLabel();
        actvPhysDurationTxt = new JTextField();
        jPanel3 = new JPanel();
        label11 = new Label();
        label12 = new Label();
        heightTxt = new TextField();
        waistSizeTxt = new TextField();
        label13 = new Label();
        weigthTxt = new TextField();
        hipSizeTxt = new TextField();
        label14 = new Label();
        label15 = new Label();
        riskTxt = new TextField();
        dxTxt = new TextField();
        label16 = new Label();
        label17 = new Label();
        label18 = new Label();
        label19 = new Label();
        label20 = new Label();
        jPanel5 = new JPanel();
        sobrepeso_checkbox = new Checkbox();
        obesidad_checkbox = new Checkbox();
        cancer_checkbox = new Checkbox();
        diabetes_checkbox = new Checkbox();
        alcoholismo_checkbox = new Checkbox();
        hiper_checkbox = new Checkbox();
        cardiopatia_checkbox = new Checkbox();
        dislipidemias_checkbox = new Checkbox();
        enfhepaticas_checkbox = new Checkbox();
        enfrespiratorias_checkbox = new Checkbox();
        enfrenales_checkbox = new Checkbox();
        otro_checkbox = new Checkbox();
        label7 = new Label();
        nauseas_checkbox = new Checkbox();
        diarrea_checkbox = new Checkbox();
        cansancio_checkbox = new Checkbox();
        vomito_checkbox = new Checkbox();
        profmasticacion_checkbox = new Checkbox();
        glucion_checkbox = new Checkbox();
        estomacal_checkbox = new Checkbox();
        estreF1imiento_checkbox = new Checkbox();
        gastritis_checkbox = new Checkbox();
        mareos_checkbox = new Checkbox();
        alteracion_checkbox = new Checkbox();
        indigestion_checkbox = new Checkbox();
        jPanel4 = new JPanel();
        habitsYesNoBox03 = new JComboBox();
        label_saltar = new JLabel();
        habitsYesNoBox01 = new JComboBox();
        horarios_comida = new JLabel();
        colaciones = new JLabel();
        colationsBox = new JComboBox();
        comes = new JLabel();
        eatCountBox = new JComboBox();
        entre_comidas = new JLabel();
        habitsYesNoBox02 = new JComboBox();
        jScrollPane15 = new JScrollPane();
        hungryHourTxt = new JTextPane();
        hambre = new JLabel();
        lugar_comer = new JLabel();
        prepara = new JLabel();
        jScrollPane16 = new JScrollPane();
        palceEatTxt = new JTextPane();
        jScrollPane3 = new JScrollPane();
        whoFoodsTxt = new JTextPane();
        jScrollPane4 = new JScrollPane();
        watterTxt = new JTextPane();
        agua = new JLabel();
        frecuencia_fumas = new JLabel();
        frecuencia = new JLabel();
        drinkFrequentyBox = new JComboBox();
        smokeFreqTxt = new JComboBox();
        label_saltar1 = new JLabel();
        jTabbedPane3 = new JTabbedPane();
        jPanel9 = new JPanel();
        label36 = new Label();
        label37 = new Label();
        Yogurth_Label18 = new JLabel();
        pescadoType = new JTextField();
        Yogurth_Label19 = new JLabel();
        jamonType = new JTextField();
        Yogurth_Label20 = new JLabel();
        salchichaType = new JTextField();
        quesoType = new JTextField();
        Yogurth_Label21 = new JLabel();
        Yogurth_Label22 = new JLabel();
        Yogurth_Label23 = new JLabel();
        azucarType = new JTextField();
        grasasType = new JTextField();
        dulcesType = new JTextField();
        papasType = new JTextField();
        otrosType = new JTextField();
        refrescosType = new JTextField();
        comidaType = new JTextField();
        jLabel22 = new JLabel();
        jLabel23 = new JLabel();
        jLabel24 = new JLabel();
        jLabel25 = new JLabel();
        jLabel26 = new JLabel();
        label38 = new Label();
        label39 = new Label();
        pescadoDay = new JTextField();
        jamonDay = new JTextField();
        salchichaDay = new JTextField();
        grasasDay = new JTextField();
        azucarDay = new JTextField();
        quesoDay = new JTextField();
        comidaDay = new JTextField();
        papasDay = new JTextField();
        dulcesDay = new JTextField();
        refrescosDay = new JTextField();
        otrosDay = new JTextField();
        pescadoWeek = new JTextField();
        jamonWeek = new JTextField();
        salchichaWeek = new JTextField();
        quesoWeek = new JTextField();
        azucarWeek = new JTextField();
        grasasWeek = new JTextField();
        dulcesWeek = new JTextField();
        comidaWeek = new JTextField();
        refrescosWeek = new JTextField();
        otrosWeek = new JTextField();
        azucarMonth = new JTextField();
        otrosMonth = new JTextField();
        pescadoMonth = new JTextField();
        grasasMonth = new JTextField();
        refrescosMonth = new JTextField();
        dulcesMonth = new JTextField();
        comidaMonth = new JTextField();
        papasMonth = new JTextField();
        quesoMonth = new JTextField();
        jamonMonth = new JTextField();
        label40 = new Label();
        salchichaMonth = new JTextField();
        papasWeek = new JTextField();
        jPanel7 = new JPanel();
        label31 = new Label();
        label32 = new Label();
        Yogurth_Label12 = new JLabel();
        yogurthType = new JTextField();
        Yogurth_Label13 = new JLabel();
        frutaType = new JTextField();
        Yogurth_Label14 = new JLabel();
        verduraType = new JTextField();
        tortillaType = new JTextField();
        Yogurth_Label15 = new JLabel();
        Yogurth_Label16 = new JLabel();
        Yogurth_Label17 = new JLabel();
        panType = new JTextField();
        pastasType = new JTextField();
        arrozType = new JTextField();
        cerealType = new JTextField();
        huevosType = new JTextField();
        polloType = new JTextField();
        carnesType = new JTextField();
        jLabel17 = new JLabel();
        jLabel18 = new JLabel();
        jLabel19 = new JLabel();
        jLabel20 = new JLabel();
        jLabel21 = new JLabel();
        label33 = new Label();
        label34 = new Label();
        yogurthDay = new JTextField();
        frutaDay = new JTextField();
        verduraDay = new JTextField();
        pastasDay = new JTextField();
        panDay = new JTextField();
        tortillaDay = new JTextField();
        carnesDay = new JTextField();
        cerealDay = new JTextField();
        arrozDay = new JTextField();
        polloDay = new JTextField();
        huevosDay = new JTextField();
        frutaWeek = new JTextField();
        verduraWeek = new JTextField();
        tortillaWeek = new JTextField();
        panWeek = new JTextField();
        pastasWeek = new JTextField();
        arrozWeek = new JTextField();
        cerealWeek = new JTextField();
        carnesWeek = new JTextField();
        polloWeek = new JTextField();
        huevosWeek = new JTextField();
        panMonth = new JTextField();
        huevosMonth = new JTextField();
        frutaMonth = new JTextField();
        pastasMonth = new JTextField();
        polloMonth = new JTextField();
        arrozMonth = new JTextField();
        carnesMonth = new JTextField();
        cerealMonth = new JTextField();
        tortillaMonth = new JTextField();
        verduraMonth = new JTextField();
        label35 = new Label();
        yogurthWeek = new JTextField();
        yogurthMonth = new JTextField();
        addBtn = new JButton();
        setDefaultCloseOperation(3);
        cancelBtn.setText("Cancel");
        jTabbedPane1.setFont(new Font("Dialog", 1, 16));
        label1.setAlignment(2);
        label1.setFont(new Font("Dialog", 1, 16));
        label1.setText("Nombre");
        label2.setAlignment(2);
        label2.setFont(new Font("Dialog", 1, 16));
        label2.setText("Edad");
        label3.setAlignment(2);
        label3.setFont(new Font("Dialog", 1, 16));
        label3.setText("Correo");
        label4.setAlignment(2);
        label4.setFont(new Font("Dialog", 1, 16));
        label4.setText("G\351nero");
        nameTxt.setFont(new Font("Dialog", 0, 16));
        yearsTxt.setFont(new Font("Dialog", 0, 16));
        eMailTxt.setFont(new Font("Dialog", 0, 16));
        label5.setAlignment(2);
        label5.setFont(new Font("Dialog", 1, 16));
        label5.setText("Tel\351fono 1");
        phone0Txt.setFont(new Font("Dialog", 0, 16));
        sexFem.setFont(new Font("Dialog", 0, 16));
        sexFem.setSelected(true);
        sexFem.setText("Femenino");
        sexMale.setFont(new Font("Dialog", 0, 16));
        sexMale.setText("Masculino");
        label6.setAlignment(2);
        label6.setFont(new Font("Dialog", 1, 16));
        label6.setText("Direcci\363n");
        adressTxt.setFont(new Font("Dialog", 0, 16));
        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(jPanel1Layout.createSequentialGroup().addComponent(label4, -2, 130, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(sexFem).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, -1, 32767).addComponent(sexMale)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(label1, -2, 130, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(nameTxt, -2, 250, -2)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(label2, -2, 130, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(yearsTxt, -2, 250, -2)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(label3, -2, 130, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(eMailTxt, -2, 250, -2))).addGap(37, 37, 37).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(label5, -2, 130, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(phone0Txt, -2, 250, -2)).addGroup(jPanel1Layout.createSequentialGroup().addComponent(label6, -2, 130, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(adressTxt, -2, 250, -2))).addContainerGap(84, 32767)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(36, 36, 36).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label1, -2, 30, -2).addComponent(nameTxt, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label2, -2, 30, -2)).addComponent(yearsTxt, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label3, -2, 30, -2)).addComponent(eMailTxt, -2, 30, -2).addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label5, -2, 30, -2).addComponent(phone0Txt, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label6, -2, 30, -2).addComponent(adressTxt, -2, 30, -2)).addGap(40, 40, 40))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label4, -2, 30, -2).addComponent(sexMale).addComponent(sexFem)).addContainerGap(327, 32767)));
        jTabbedPane1.addTab("Personales", jPanel1);
        jPanel2.setForeground(new Color(1, 1, 1));
        jLabel1.setFont(new Font("Dialog", 1, 16));
        jLabel1.setForeground(new Color(1, 1, 1));
        jLabel1.setHorizontalAlignment(0);
        jLabel1.setText("Padecimientos actuales");
        jLabel2.setFont(new Font("Dialog", 1, 16));
        jLabel2.setForeground(new Color(1, 1, 1));
        jLabel2.setHorizontalAlignment(0);
        jLabel2.setText("Tratamiento actual");
        jLabel3.setFont(new Font("Dialog", 1, 16));
        jLabel3.setForeground(new Color(1, 1, 1));
        jLabel3.setHorizontalAlignment(0);
        jLabel3.setText("Cirug\355as");
        jLabel4.setFont(new Font("Dialog", 1, 16));
        jLabel4.setForeground(new Color(1, 1, 1));
        jLabel4.setHorizontalAlignment(0);
        jLabel4.setText("Suplementos o complementos");
        actualTreatmentTxt.setColumns(20);
        actualTreatmentTxt.setRows(5);
        jScrollPane5.setViewportView(actualTreatmentTxt);
        actualAilmentTxt.setColumns(20);
        actualAilmentTxt.setRows(5);
        jScrollPane6.setViewportView(actualAilmentTxt);
        complementsTxt.setColumns(20);
        complementsTxt.setRows(5);
        jScrollPane7.setViewportView(complementsTxt);
        surgeriesTxt.setColumns(20);
        surgeriesTxt.setRows(5);
        jScrollPane8.setViewportView(surgeriesTxt);
        label_fisica.setFont(new Font("Dialog", 1, 16));
        label_fisica.setForeground(new Color(1, 1, 1));
        label_fisica.setText("\277Con qu\351 frecuencia realizas la actividad f\355sica?");
        fisica.setFont(new Font("Dialog", 1, 16));
        fisica.setForeground(new Color(1, 1, 1));
        fisica.setText("\277Realizas alguna actividad f\355sica?");
        actvPhysBox.setFont(new Font("Dialog", 0, 16));
        actvPhysBox.setForeground(new Color(1, 1, 1));
        actvPhysBox.setModel(new DefaultComboBoxModel(new String[] {
            "Si", "No"
        }));
        atcvPhysFrequenBox.setFont(new Font("Dialog", 0, 16));
        atcvPhysFrequenBox.setForeground(new Color(1, 1, 1));
        atcvPhysFrequenBox.setModel(new DefaultComboBoxModel(new String[] {
            "una vez por semana", "dos veces por semana", "tres veces por semana", "cuatro veces por semana", "todos los dias"
        }));
        cual_fisica.setFont(new Font("Dialog", 1, 16));
        cual_fisica.setForeground(new Color(1, 1, 1));
        cual_fisica.setText("\277Cu\341l?");
        jScrollPane12.setForeground(new Color(1, 1, 1));
        actvPhysTxt.setFont(new Font("Dialog", 0, 16));
        jScrollPane12.setViewportView(actvPhysTxt);
        duracion.setFont(new Font("Dialog", 1, 16));
        duracion.setForeground(new Color(1, 1, 1));
        duracion.setText("Duraci\363n");
        actvPhysDurationTxt.setFont(new Font("Dialog", 0, 16));
        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addGroup(jPanel2Layout.createSequentialGroup().addGap(60, 60, 60).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jScrollPane8, -2, 400, -2).addGap(18, 18, 18).addComponent(jScrollPane7, -2, 400, -2)).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel3, -2, 400, -2).addGap(18, 18, 18).addComponent(jLabel4, -2, 400, -2)).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(jScrollPane6, -1, 400, 32767).addComponent(jLabel1, -1, -1, 32767)).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel2, -2, 400, -2)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jScrollPane5, -2, 400, -2)))))).addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(fisica).addGap(18, 18, 18).addComponent(actvPhysBox, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cual_fisica).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addComponent(label_fisica).addGap(25, 25, 25))).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addComponent(atcvPhysFrequenBox, -2, -1, -2).addGap(224, 224, 224)).addGroup(jPanel2Layout.createSequentialGroup().addComponent(jScrollPane12).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(duracion).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(actvPhysDurationTxt, -2, 108, -2))))).addContainerGap(-1, 32767)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGap(24, 24, 24).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1, -2, 30, -2).addComponent(jLabel2, -2, 30, -2)).addGap(12, 12, 12).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jScrollPane6, -1, 100, 32767).addComponent(jScrollPane5)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, 32767).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, -2, 30, -2).addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jScrollPane8).addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, -2, 100, -2)).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel2Layout.createSequentialGroup().addGap(8, 8, 8).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(fisica).addComponent(actvPhysBox, -2, -1, -2).addComponent(cual_fisica))).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup().addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(duracion, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(actvPhysDurationTxt, javax.swing.GroupLayout.Alignment.TRAILING, -2, -1, -2))))).addGroup(jPanel2Layout.createSequentialGroup().addContainerGap(-1, 32767).addComponent(jScrollPane12, -2, -1, -2))).addGap(18, 18, 18).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(label_fisica).addComponent(atcvPhysFrequenBox, -2, -1, -2)).addContainerGap(97, 32767)));
        jTabbedPane1.addTab("Antecedentes", jPanel2);
        label11.setAlignment(2);
        label11.setFont(new Font("Dialog", 1, 16));
        label11.setText("Peso");
        label12.setAlignment(2);
        label12.setFont(new Font("Dialog", 1, 16));
        label12.setText("Altura");
        heightTxt.setFont(new Font("Dialog", 0, 16));
        waistSizeTxt.setFont(new Font("Dialog", 0, 16));
        label13.setAlignment(2);
        label13.setFont(new Font("Dialog", 1, 16));
        label13.setText("Medida de la cintura");
        weigthTxt.setFont(new Font("Dialog", 0, 16));
        hipSizeTxt.setFont(new Font("Dialog", 0, 16));
        label14.setAlignment(2);
        label14.setFont(new Font("Dialog", 1, 16));
        label14.setText("Medida de la cadera");
        label15.setAlignment(2);
        label15.setFont(new Font("Dialog", 1, 16));
        label15.setText("Riesgo de comorbilidad");
        riskTxt.setFont(new Font("Dialog", 0, 16));
        dxTxt.setFont(new Font("Dialog", 0, 16));
        label16.setAlignment(2);
        label16.setFont(new Font("Dialog", 1, 16));
        label16.setText("Dx");
        label17.setFont(new Font("Dialog", 1, 16));
        label17.setText("kilogramos");
        label18.setFont(new Font("Dialog", 1, 16));
        label18.setText("centimetros");
        label19.setFont(new Font("Dialog", 1, 16));
        label19.setText("centimetros");
        label20.setFont(new Font("Dialog", 1, 16));
        label20.setText("centimetros");
        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(jPanel3Layout.createSequentialGroup().addComponent(label11, -2, 220, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(weigthTxt, -2, 250, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label17, -1, -1, 32767)).addGroup(jPanel3Layout.createSequentialGroup().addComponent(label12, -2, 220, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(heightTxt, -2, 250, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label19, -1, -1, 32767)).addGroup(jPanel3Layout.createSequentialGroup().addComponent(label13, -2, 220, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(waistSizeTxt, -2, 250, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label18, -1, -1, 32767)).addGroup(jPanel3Layout.createSequentialGroup().addComponent(label14, -2, 220, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(hipSizeTxt, -2, 250, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label20, -1, -1, 32767)).addGroup(jPanel3Layout.createSequentialGroup().addComponent(label15, -2, 220, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(riskTxt, -2, 250, -2)).addGroup(jPanel3Layout.createSequentialGroup().addComponent(label16, -2, 220, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(dxTxt, -2, 250, -2))).addContainerGap(299, 32767)));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel3Layout.createSequentialGroup().addGap(46, 46, 46).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label11, -2, 30, -2).addComponent(weigthTxt, -2, 30, -2).addComponent(label17, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label12, -2, 30, -2).addComponent(label19, javax.swing.GroupLayout.Alignment.TRAILING, -2, 30, -2))).addComponent(heightTxt, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label13, -2, 30, -2).addComponent(label18, javax.swing.GroupLayout.Alignment.TRAILING, -2, 30, -2))).addComponent(waistSizeTxt, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label14, -2, 30, -2).addComponent(hipSizeTxt, -2, 30, -2))).addComponent(label20, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label15, -2, 30, -2).addComponent(riskTxt, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label16, -2, 30, -2).addComponent(dxTxt, -2, 30, -2)).addContainerGap(237, 32767)));
        jTabbedPane1.addTab("Antropom\351tricos", jPanel3);
        sobrepeso_checkbox.setFont(new Font("Dialog", 1, 16));
        sobrepeso_checkbox.setLabel("sobrepeso");
        obesidad_checkbox.setFont(new Font("Dialog", 1, 16));
        obesidad_checkbox.setLabel("obesidad");
        cancer_checkbox.setFont(new Font("Dialog", 1, 16));
        cancer_checkbox.setLabel("c\341ncer");
        diabetes_checkbox.setFont(new Font("Dialog", 1, 16));
        diabetes_checkbox.setLabel("diabetes");
        alcoholismo_checkbox.setFont(new Font("Dialog", 1, 16));
        alcoholismo_checkbox.setLabel("alcoholismo");
        hiper_checkbox.setFont(new Font("Dialog", 1, 16));
        hiper_checkbox.setLabel("hipertensi\363n arterial");
        cardiopatia_checkbox.setFont(new Font("Dialog", 1, 16));
        cardiopatia_checkbox.setLabel("cardiopatia");
        dislipidemias_checkbox.setFont(new Font("Dialog", 1, 16));
        dislipidemias_checkbox.setLabel("disliepidemia");
        enfhepaticas_checkbox.setFont(new Font("Dialog", 1, 16));
        enfhepaticas_checkbox.setLabel("enfermedades hep\341ticas");
        enfrespiratorias_checkbox.setFont(new Font("Dialog", 1, 16));
        enfrespiratorias_checkbox.setLabel("enfermedades respiratorias");
        enfrenales_checkbox.setFont(new Font("Dialog", 1, 16));
        enfrenales_checkbox.setLabel("enfermedades renales");
        otro_checkbox.setFont(new Font("Dialog", 1, 16));
        otro_checkbox.setLabel("otro");
        label7.setFont(new Font("Dialog", 1, 22));
        label7.setText("S\355ntomas que presentan actualmente");
        nauseas_checkbox.setFont(new Font("Dialog", 1, 16));
        nauseas_checkbox.setLabel("Na\372seas");
        diarrea_checkbox.setFont(new Font("Dialog", 1, 16));
        diarrea_checkbox.setLabel("diarrea");
        cansancio_checkbox.setFont(new Font("Dialog", 1, 16));
        cansancio_checkbox.setLabel("cansancio");
        vomito_checkbox.setFont(new Font("Dialog", 1, 16));
        vomito_checkbox.setLabel("v\363mito");
        profmasticacion_checkbox.setFont(new Font("Dialog", 1, 16));
        profmasticacion_checkbox.setLabel("Problemas de masticaci\363n");
        glucion_checkbox.setFont(new Font("Dialog", 1, 16));
        glucion_checkbox.setLabel("problemas de gluci\363n");
        estomacal_checkbox.setFont(new Font("Dialog", 1, 16));
        estomacal_checkbox.setLabel("inflamaci\363n estomacal");
        estreF1imiento_checkbox.setFont(new Font("Dialog", 1, 16));
        estreF1imiento_checkbox.setLabel("estre\361imiento");
        gastritis_checkbox.setFont(new Font("Dialog", 1, 16));
        gastritis_checkbox.setLabel("gastritis");
        mareos_checkbox.setFont(new Font("Dialog", 1, 16));
        mareos_checkbox.setLabel("mareos");
        alteracion_checkbox.setFont(new Font("Dialog", 1, 16));
        alteracion_checkbox.setLabel("alteraciones del apetito");
        indigestion_checkbox.setFont(new Font("Dialog", 1, 16));
        indigestion_checkbox.setLabel("flatulencia, indigesti\363n");
        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGap(14, 14, 14).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(sobrepeso_checkbox, -2, -1, -2).addComponent(obesidad_checkbox, -2, -1, -2).addComponent(cancer_checkbox, -2, -1, -2).addComponent(diabetes_checkbox, -2, -1, -2)).addGap(46, 46, 46).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(dislipidemias_checkbox, -2, -1, -2).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(alcoholismo_checkbox, -2, -1, -2).addComponent(hiper_checkbox, -2, -1, -2).addComponent(cardiopatia_checkbox, -2, -1, -2)).addGap(57, 57, 57).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(enfrenales_checkbox, -2, -1, -2).addComponent(enfrespiratorias_checkbox, -2, -1, -2).addComponent(enfhepaticas_checkbox, -2, -1, -2).addComponent(otro_checkbox, -2, -1, -2))))).addGroup(jPanel5Layout.createSequentialGroup().addContainerGap().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup().addComponent(diarrea_checkbox, -2, -1, -2).addGap(114, 114, 114)).addGroup(jPanel5Layout.createSequentialGroup().addComponent(vomito_checkbox, -2, -1, -2).addGap(117, 117, 117))).addGroup(jPanel5Layout.createSequentialGroup().addComponent(nauseas_checkbox, -2, -1, -2).addGap(102, 102, 102))).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(glucion_checkbox, -2, -1, -2).addComponent(estomacal_checkbox, -2, -1, -2).addComponent(profmasticacion_checkbox, -2, -1, -2)).addGap(15, 15, 15).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(cansancio_checkbox, -2, -1, -2).addComponent(estreF1imiento_checkbox, -2, -1, -2).addComponent(gastritis_checkbox, -2, -1, -2)).addGap(54, 54, 54).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(indigestion_checkbox, -2, -1, -2).addComponent(alteracion_checkbox, -2, -1, -2).addComponent(mareos_checkbox, -2, -1, -2))).addComponent(label7, -2, -1, -2)))).addContainerGap(-1, 32767)));
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup().addGap(22, 22, 22).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(sobrepeso_checkbox, -2, -1, -2).addComponent(alcoholismo_checkbox, -2, -1, -2).addComponent(enfhepaticas_checkbox, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(obesidad_checkbox, -2, -1, -2).addComponent(hiper_checkbox, -2, -1, -2).addComponent(enfrespiratorias_checkbox, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(cancer_checkbox, -2, -1, -2).addComponent(cardiopatia_checkbox, -2, -1, -2).addComponent(enfrenales_checkbox, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(otro_checkbox, -2, -1, -2).addComponent(dislipidemias_checkbox, -2, -1, -2).addComponent(diabetes_checkbox, -2, -1, -2)).addGap(23, 23, 23).addComponent(label7, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(nauseas_checkbox, -2, -1, -2).addComponent(cansancio_checkbox, -2, -1, -2).addComponent(mareos_checkbox, -2, -1, -2).addComponent(profmasticacion_checkbox, -2, -1, -2)).addGap(25, 25, 25).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(vomito_checkbox, -2, -1, -2).addComponent(glucion_checkbox, -2, -1, -2).addComponent(estreF1imiento_checkbox, -2, -1, -2).addComponent(alteracion_checkbox, -2, -1, -2)).addGap(28, 28, 28).addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(estomacal_checkbox, -2, -1, -2).addComponent(gastritis_checkbox, -2, -1, -2).addComponent(indigestion_checkbox, -2, -1, -2).addComponent(diarrea_checkbox, -2, -1, -2)).addContainerGap(183, 32767)));
        jTabbedPane1.addTab("Antecedentes heredofamiliares", jPanel5);
        habitsYesNoBox03.setFont(new Font("Dialog", 0, 16));
        habitsYesNoBox03.setModel(new DefaultComboBoxModel(new String[] {
            "S\355", "No"
        }));
        label_saltar.setFont(new Font("Dialog", 1, 16));
        label_saltar.setForeground(new Color(1, 1, 1));
        label_saltar.setText("Acostumbras a saltarte comidas?");
        habitsYesNoBox01.setFont(new Font("Dialog", 0, 16));
        habitsYesNoBox01.setModel(new DefaultComboBoxModel(new String[] {
            "S\355", "No", "De lunes a viernes"
        }));
        horarios_comida.setFont(new Font("Dialog", 1, 16));
        horarios_comida.setForeground(new Color(1, 1, 1));
        horarios_comida.setText("Sus horarios de comida son fijos");
        colaciones.setFont(new Font("Dialog", 1, 16));
        colaciones.setForeground(new Color(1, 1, 1));
        colaciones.setText("\277Cu\341ntas colaciones realizas?");
        colationsBox.setFont(new Font("Dialog", 0, 16));
        colationsBox.setModel(new DefaultComboBoxModel(new String[] {
            "0", "1", "2", "3", "4", "5", "6"
        }));
        comes.setFont(new Font("Dialog", 1, 16));
        comes.setForeground(new Color(1, 1, 1));
        comes.setText("\277Cu\341ntas veces comes al d\355a?");
        eatCountBox.setFont(new Font("Dialog", 0, 16));
        eatCountBox.setModel(new DefaultComboBoxModel(new String[] {
            "1", "2", "3", "4", "5", "6"
        }));
        entre_comidas.setFont(new Font("Dialog", 1, 16));
        entre_comidas.setForeground(new Color(1, 1, 1));
        entre_comidas.setText("\277Acostumbras a comer entre comidas?");
        habitsYesNoBox02.setFont(new Font("Dialog", 0, 16));
        habitsYesNoBox02.setModel(new DefaultComboBoxModel(new String[] {
            "S\355", "No"
        }));
        hungryHourTxt.setFont(new Font("Dialog", 0, 16));
        jScrollPane15.setViewportView(hungryHourTxt);
        hambre.setFont(new Font("Dialog", 1, 16));
        hambre.setForeground(new Color(1, 1, 1));
        hambre.setText("\277A qu\351 hora siente m\341s hambre?");
        lugar_comer.setFont(new Font("Dialog", 1, 16));
        lugar_comer.setForeground(new Color(1, 1, 1));
        lugar_comer.setText("Lugar donde acostumbra comer regularmente");
        prepara.setFont(new Font("Dialog", 1, 16));
        prepara.setForeground(new Color(1, 1, 1));
        prepara.setText("\277Qui\351n prepara tus alimentos?");
        palceEatTxt.setFont(new Font("Dialog", 0, 16));
        jScrollPane16.setViewportView(palceEatTxt);
        whoFoodsTxt.setFont(new Font("Dialog", 0, 16));
        jScrollPane3.setViewportView(whoFoodsTxt);
        watterTxt.setFont(new Font("Dialog", 0, 16));
        jScrollPane4.setViewportView(watterTxt);
        agua.setFont(new Font("Dialog", 1, 16));
        agua.setForeground(new Color(1, 1, 1));
        agua.setText("Consumo de agua");
        frecuencia_fumas.setFont(new Font("Dialog", 1, 16));
        frecuencia_fumas.setForeground(new Color(1, 1, 1));
        frecuencia_fumas.setText("\277Con qu\351 frecuencia fumas?");
        frecuencia.setFont(new Font("Dialog", 1, 16));
        frecuencia.setForeground(new Color(1, 1, 1));
        frecuencia.setText("\277Con qu\351 frecuencia tomas bebida alcoh\363licas?");
        drinkFrequentyBox.setFont(new Font("Dialog", 0, 16));
        drinkFrequentyBox.setModel(new DefaultComboBoxModel(new String[] {
            "Nunca", "Una vez por semana", "dos veces por semana", "tres veces por semana", "cada ocho dias", "una vez por mes", "una vez por a\361o", "dos veces por a\361o"
        }));
        smokeFreqTxt.setFont(new Font("Dialog", 0, 16));
        smokeFreqTxt.setModel(new DefaultComboBoxModel(new String[] {
            "Nunca", "Una vez por semana", "dos veces por semana", "tres veces por semana", "cada ocho dias", "una vez por mes", "una vez por a\361o", "dos veces por a\361o"
        }));
        label_saltar1.setFont(new Font("Dialog", 1, 16));
        label_saltar1.setForeground(new Color(1, 1, 1));
        label_saltar1.setText("Litros al d\355a");
        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(frecuencia).addComponent(frecuencia_fumas).addGroup(jPanel4Layout.createSequentialGroup().addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(horarios_comida).addComponent(colaciones).addComponent(hambre).addComponent(lugar_comer).addComponent(prepara).addComponent(label_saltar).addComponent(entre_comidas).addComponent(agua).addComponent(comes)).addGap(29, 29, 29).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(eatCountBox, -2, 63, -2).addComponent(habitsYesNoBox01, -2, 63, -2).addComponent(habitsYesNoBox02, -2, -1, -2).addComponent(habitsYesNoBox03, -2, -1, -2).addComponent(colationsBox, -2, 63, -2).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel4Layout.createSequentialGroup().addComponent(jScrollPane4, -2, 218, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label_saltar1, -2, 169, -2)).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, -2, 399, -2))).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(drinkFrequentyBox, -2, -1, -2).addComponent(smokeFreqTxt, javax.swing.GroupLayout.Alignment.TRAILING, -2, -1, -2)).addComponent(jScrollPane15, -2, 399, -2)))).addContainerGap(61, 32767)));
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(comes).addComponent(eatCountBox, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(colaciones).addComponent(colationsBox, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(horarios_comida).addComponent(habitsYesNoBox01, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(entre_comidas).addComponent(habitsYesNoBox02, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(habitsYesNoBox03, javax.swing.GroupLayout.Alignment.TRAILING, -2, -1, -2).addComponent(label_saltar)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jScrollPane15, -2, -1, -2).addComponent(hambre)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jScrollPane16, -2, -1, -2).addComponent(lugar_comer)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jScrollPane3, -2, -1, -2).addComponent(prepara)).addGap(9, 9, 9).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addGap(8, 8, 8).addComponent(label_saltar1)).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(agua).addComponent(jScrollPane4, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel4Layout.createSequentialGroup().addComponent(frecuencia).addGap(29, 29, 29).addComponent(frecuencia_fumas)).addGroup(jPanel4Layout.createSequentialGroup().addComponent(drinkFrequentyBox, -2, -1, -2).addGap(17, 17, 17).addComponent(smokeFreqTxt, -2, -1, -2))).addContainerGap(96, 32767)));
        jTabbedPane1.addTab("H\341bitos", jPanel4);
        label36.setFont(new Font("Dialog", 1, 16));
        label36.setText("Alimento");
        label37.setFont(new Font("Dialog", 1, 16));
        label37.setText("Tipo");
        Yogurth_Label18.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label18.setText("Pescado");
        pescadoType.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label19.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label19.setText("Jam\363n");
        jamonType.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label20.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label20.setText("Salchicha");
        salchichaType.setFont(new Font("Ubuntu", 0, 16));
        quesoType.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label21.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label21.setText("Grasas");
        Yogurth_Label22.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label22.setText("Queso");
        Yogurth_Label23.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label23.setText("Az\372car");
        azucarType.setFont(new Font("Ubuntu", 0, 16));
        grasasType.setFont(new Font("Ubuntu", 0, 16));
        dulcesType.setFont(new Font("Ubuntu", 0, 16));
        papasType.setFont(new Font("Ubuntu", 0, 16));
        otrosType.setFont(new Font("Ubuntu", 0, 16));
        refrescosType.setFont(new Font("Ubuntu", 0, 16));
        comidaType.setFont(new Font("Ubuntu", 0, 16));
        jLabel22.setFont(new Font("Ubuntu", 0, 16));
        jLabel22.setText("Dulces o golosinas");
        jLabel23.setFont(new Font("Ubuntu", 0, 16));
        jLabel23.setText("Papas fritas");
        jLabel24.setFont(new Font("Ubuntu", 0, 16));
        jLabel24.setText("Comida r\341pida");
        jLabel25.setFont(new Font("Ubuntu", 0, 16));
        jLabel25.setText("Refrescos");
        jLabel26.setFont(new Font("Ubuntu", 0, 16));
        jLabel26.setText("Otros");
        label38.setAlignment(1);
        label38.setFont(new Font("Dialog", 1, 16));
        label38.setText("Al d\355a");
        label39.setFont(new Font("Dialog", 1, 16));
        label39.setText("A la semana");
        pescadoDay.setFont(new Font("Ubuntu", 0, 16));
        jamonDay.setFont(new Font("Ubuntu", 0, 16));
        salchichaDay.setFont(new Font("Ubuntu", 0, 16));
        grasasDay.setFont(new Font("Ubuntu", 0, 16));
        azucarDay.setFont(new Font("Ubuntu", 0, 16));
        quesoDay.setFont(new Font("Ubuntu", 0, 16));
        comidaDay.setFont(new Font("Ubuntu", 0, 16));
        papasDay.setFont(new Font("Ubuntu", 0, 16));
        dulcesDay.setFont(new Font("Ubuntu", 0, 16));
        refrescosDay.setFont(new Font("Ubuntu", 0, 16));
        otrosDay.setFont(new Font("Ubuntu", 0, 16));
        pescadoWeek.setFont(new Font("Ubuntu", 0, 16));
        jamonWeek.setFont(new Font("Ubuntu", 0, 16));
        salchichaWeek.setFont(new Font("Ubuntu", 0, 16));
        quesoWeek.setFont(new Font("Ubuntu", 0, 16));
        azucarWeek.setFont(new Font("Ubuntu", 0, 16));
        grasasWeek.setFont(new Font("Ubuntu", 0, 16));
        dulcesWeek.setFont(new Font("Ubuntu", 0, 16));
        comidaWeek.setFont(new Font("Ubuntu", 0, 16));
        refrescosWeek.setFont(new Font("Ubuntu", 0, 16));
        otrosWeek.setFont(new Font("Ubuntu", 0, 16));
        azucarMonth.setFont(new Font("Ubuntu", 0, 16));
        otrosMonth.setFont(new Font("Ubuntu", 0, 16));
        pescadoMonth.setFont(new Font("Ubuntu", 0, 16));
        grasasMonth.setFont(new Font("Ubuntu", 0, 16));
        refrescosMonth.setFont(new Font("Ubuntu", 0, 16));
        dulcesMonth.setFont(new Font("Ubuntu", 0, 16));
        comidaMonth.setFont(new Font("Ubuntu", 0, 16));
        papasMonth.setFont(new Font("Ubuntu", 0, 16));
        quesoMonth.setFont(new Font("Ubuntu", 0, 16));
        jamonMonth.setFont(new Font("Ubuntu", 0, 16));
        label40.setFont(new Font("Dialog", 1, 16));
        label40.setText("Al mes");
        salchichaMonth.setFont(new Font("Ubuntu", 0, 16));
        papasWeek.setFont(new Font("Ubuntu", 0, 16));
        GroupLayout jPanel9Layout = new GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addContainerGap().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label36, -2, 200, -2).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(Yogurth_Label18, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label23, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label22, -1, -1, 32767).addComponent(Yogurth_Label20, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label19, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label21, javax.swing.GroupLayout.Alignment.LEADING, -1, 200, 32767).addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label37, -1, -1, 32767).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(dulcesType, -1, 250, 32767).addComponent(otrosType, -1, 250, 32767).addComponent(refrescosType, -1, 250, 32767).addComponent(comidaType, -1, 250, 32767).addComponent(papasType, -1, 250, 32767).addComponent(grasasType).addComponent(azucarType).addComponent(quesoType).addComponent(salchichaType).addComponent(jamonType)).addComponent(pescadoType, -2, 250, -2)).addGap(0, 0, 32767))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(pescadoDay, -2, 120, -2).addComponent(jamonDay, -2, 120, -2).addComponent(salchichaDay, -2, 120, -2).addComponent(quesoDay, -2, 120, -2).addComponent(azucarDay, -2, 120, -2).addComponent(grasasDay, -2, 120, -2).addComponent(dulcesDay, -2, 120, -2).addComponent(papasDay, -2, 120, -2).addComponent(comidaDay, -2, 120, -2).addComponent(refrescosDay, -2, 120, -2).addComponent(otrosDay, -2, 120, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(salchichaWeek, -2, 120, -2).addComponent(quesoWeek, -2, 120, -2).addComponent(azucarWeek, -2, 120, -2).addComponent(grasasWeek, -2, 120, -2).addComponent(dulcesWeek, -2, 120, -2).addComponent(comidaWeek, -2, 120, -2).addComponent(refrescosWeek, -2, 120, -2).addComponent(otrosWeek, -2, 120, -2).addComponent(jamonWeek, javax.swing.GroupLayout.Alignment.TRAILING, -2, 120, -2).addComponent(pescadoWeek, javax.swing.GroupLayout.Alignment.TRAILING, -2, 120, -2)).addComponent(papasWeek, -2, 120, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, -1, 32767)).addGroup(jPanel9Layout.createSequentialGroup().addComponent(label38, -1, -1, 32767).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label39, -2, 120, -2).addGap(14, 14, 14))).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addComponent(label40, -2, 120, -2).addContainerGap()).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(salchichaMonth, javax.swing.GroupLayout.Alignment.LEADING).addComponent(jamonMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(quesoMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(azucarMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(grasasMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(dulcesMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(papasMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(comidaMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(refrescosMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(otrosMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767).addComponent(pescadoMonth, javax.swing.GroupLayout.Alignment.LEADING, -1, 120, 32767)).addGap(0, 23, 32767)))));
        jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addContainerGap().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label39, -2, 30, -2).addComponent(label37, -2, 30, -2).addComponent(label36, -2, 30, -2).addComponent(label38, -2, 30, -2).addComponent(label40, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label18).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(pescadoType, -2, -1, -2).addComponent(pescadoDay, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label19).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jamonType, -2, -1, -2).addComponent(jamonDay, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label20).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(salchichaType, -2, -1, -2).addComponent(salchichaDay, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label22).addComponent(quesoType, -2, -1, -2)).addGap(18, 18, 18).addComponent(Yogurth_Label23, -2, 17, -2).addGap(18, 18, 18).addComponent(Yogurth_Label21).addGap(18, 18, 18).addComponent(jLabel22).addGap(18, 18, 18).addComponent(jLabel23).addGap(18, 18, 18).addComponent(jLabel24).addGap(18, 18, 18).addComponent(jLabel25).addGap(18, 18, 18).addComponent(jLabel26)).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel9Layout.createSequentialGroup().addComponent(azucarType, -2, -1, -2).addGap(6, 6, 6).addComponent(grasasType, -2, -1, -2)).addGroup(jPanel9Layout.createSequentialGroup().addComponent(quesoDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(azucarDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(grasasDay, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel9Layout.createSequentialGroup().addComponent(dulcesType, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(papasType, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(comidaType, -2, -1, -2).addGap(6, 6, 6).addComponent(refrescosType, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(otrosType, -2, -1, -2)).addGroup(jPanel9Layout.createSequentialGroup().addComponent(dulcesDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(papasDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(comidaDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(refrescosDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(otrosDay, -2, -1, -2)))))).addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(pescadoMonth, -2, -1, -2).addComponent(pescadoWeek, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jamonMonth, -2, -1, -2).addComponent(jamonWeek, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(salchichaWeek, -2, -1, -2).addComponent(salchichaMonth, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addGroup(jPanel9Layout.createSequentialGroup().addComponent(quesoWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(azucarWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(grasasWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(dulcesWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, -1, 32767).addComponent(comidaWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(refrescosWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(otrosWeek, -2, -1, -2)).addGroup(jPanel9Layout.createSequentialGroup().addComponent(quesoMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(azucarMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(grasasMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(dulcesMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(papasMonth, -2, -1, -2).addComponent(papasWeek, -2, -1, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(comidaMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(refrescosMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(otrosMonth, -2, -1, -2))))).addContainerGap(14, 32767)));
        jTabbedPane3.addTab("Dieta", jPanel9);
        label31.setFont(new Font("Dialog", 1, 16));
        label31.setText("Alimento");
        label32.setFont(new Font("Dialog", 1, 16));
        label32.setText("Tipo");
        Yogurth_Label12.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label12.setText("Yogurth");
        yogurthType.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label13.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label13.setText("Fruta");
        frutaType.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label14.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label14.setText("Verdura");
        verduraType.setFont(new Font("Ubuntu", 0, 16));
        tortillaType.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label15.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label15.setText("Pastas");
        Yogurth_Label16.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label16.setText("Tortilla");
        Yogurth_Label17.setFont(new Font("Ubuntu", 0, 16));
        Yogurth_Label17.setText("Pan");
        panType.setFont(new Font("Ubuntu", 0, 16));
        pastasType.setFont(new Font("Ubuntu", 0, 16));
        arrozType.setFont(new Font("Ubuntu", 0, 16));
        cerealType.setFont(new Font("Ubuntu", 0, 16));
        huevosType.setFont(new Font("Ubuntu", 0, 16));
        polloType.setFont(new Font("Ubuntu", 0, 16));
        carnesType.setFont(new Font("Ubuntu", 0, 16));
        jLabel17.setFont(new Font("Ubuntu", 0, 16));
        jLabel17.setText("Arroz");
        jLabel18.setFont(new Font("Ubuntu", 0, 16));
        jLabel18.setText("Cereal en las ma\361anas");
        jLabel19.setFont(new Font("Ubuntu", 0, 16));
        jLabel19.setText("Carne roja");
        jLabel20.setFont(new Font("Ubuntu", 0, 16));
        jLabel20.setText("Pollo");
        jLabel21.setFont(new Font("Ubuntu", 0, 16));
        jLabel21.setText("Huevo");
        label33.setAlignment(1);
        label33.setFont(new Font("Dialog", 1, 16));
        label33.setText("Al d\355a");
        label34.setFont(new Font("Dialog", 1, 16));
        label34.setText("A la semana");
        yogurthDay.setFont(new Font("Ubuntu", 0, 16));
        frutaDay.setFont(new Font("Ubuntu", 0, 16));
        verduraDay.setFont(new Font("Ubuntu", 0, 16));
        pastasDay.setFont(new Font("Ubuntu", 0, 16));
        panDay.setFont(new Font("Ubuntu", 0, 16));
        tortillaDay.setFont(new Font("Ubuntu", 0, 16));
        carnesDay.setFont(new Font("Ubuntu", 0, 16));
        cerealDay.setFont(new Font("Ubuntu", 0, 16));
        arrozDay.setFont(new Font("Ubuntu", 0, 16));
        polloDay.setFont(new Font("Ubuntu", 0, 16));
        huevosDay.setFont(new Font("Ubuntu", 0, 16));
        frutaWeek.setFont(new Font("Ubuntu", 0, 16));
        verduraWeek.setFont(new Font("Ubuntu", 0, 16));
        tortillaWeek.setFont(new Font("Ubuntu", 0, 16));
        panWeek.setFont(new Font("Ubuntu", 0, 16));
        pastasWeek.setFont(new Font("Ubuntu", 0, 16));
        arrozWeek.setFont(new Font("Ubuntu", 0, 16));
        cerealWeek.setFont(new Font("Ubuntu", 0, 16));
        carnesWeek.setFont(new Font("Ubuntu", 0, 16));
        polloWeek.setFont(new Font("Ubuntu", 0, 16));
        huevosWeek.setFont(new Font("Ubuntu", 0, 16));
        panMonth.setFont(new Font("Ubuntu", 0, 16));
        huevosMonth.setFont(new Font("Ubuntu", 0, 16));
        frutaMonth.setFont(new Font("Ubuntu", 0, 16));
        pastasMonth.setFont(new Font("Ubuntu", 0, 16));
        polloMonth.setFont(new Font("Ubuntu", 0, 16));
        arrozMonth.setFont(new Font("Ubuntu", 0, 16));
        carnesMonth.setFont(new Font("Ubuntu", 0, 16));
        cerealMonth.setFont(new Font("Ubuntu", 0, 16));
        tortillaMonth.setFont(new Font("Ubuntu", 0, 16));
        verduraMonth.setFont(new Font("Ubuntu", 0, 16));
        label35.setFont(new Font("Dialog", 1, 16));
        label35.setText("Al mes");
        yogurthWeek.setFont(new Font("Ubuntu", 0, 16));
        yogurthMonth.setFont(new Font("Ubuntu", 0, 16));
        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addContainerGap().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label31, -2, 200, -2).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(Yogurth_Label12, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label17, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label16, -1, -1, 32767).addComponent(Yogurth_Label14, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label13, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(Yogurth_Label15, javax.swing.GroupLayout.Alignment.LEADING, -1, 200, 32767).addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767).addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, -1, -1, 32767))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(tortillaType).addComponent(label32, -1, -1, 32767).addComponent(yogurthType).addComponent(frutaType).addComponent(verduraType).addComponent(panType).addComponent(pastasType).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(arrozType, -2, 250, -2).addComponent(huevosType, -2, 250, -2).addComponent(polloType, -2, 250, -2).addComponent(carnesType, -2, 250, -2).addComponent(cerealType, -2, 250, -2)).addGap(0, 0, 32767))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addComponent(yogurthDay, -2, 120, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(yogurthWeek, -2, 120, -2)).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(frutaDay, -2, 120, -2).addComponent(verduraDay, -2, 120, -2).addComponent(tortillaDay, -2, 120, -2).addComponent(panDay, -2, 120, -2).addComponent(pastasDay, -2, 120, -2).addComponent(arrozDay, -2, 120, -2).addComponent(cerealDay, -2, 120, -2).addComponent(carnesDay, -2, 120, -2).addComponent(polloDay, -2, 120, -2).addComponent(huevosDay, -2, 120, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(tortillaWeek, -2, 120, -2).addComponent(panWeek, -2, 120, -2).addComponent(pastasWeek, -2, 120, -2).addComponent(arrozWeek, -2, 120, -2).addComponent(cerealWeek, -2, 120, -2).addComponent(carnesWeek, -2, 120, -2).addComponent(polloWeek, -2, 120, -2).addComponent(huevosWeek, -2, 120, -2).addComponent(verduraWeek, javax.swing.GroupLayout.Alignment.TRAILING, -2, 120, -2).addComponent(frutaWeek, javax.swing.GroupLayout.Alignment.TRAILING, -2, 120, -2)))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, -1, 32767)).addGroup(jPanel7Layout.createSequentialGroup().addComponent(label33, -1, -1, 32767).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(label34, -2, 120, -2).addGap(14, 14, 14))).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(label35, -2, 120, -2).addComponent(verduraMonth, -2, 120, -2).addComponent(tortillaMonth, -2, 120, -2).addComponent(panMonth, -2, 120, -2).addComponent(pastasMonth, -2, 120, -2).addComponent(arrozMonth, -2, 120, -2).addComponent(cerealMonth, -2, 120, -2).addComponent(carnesMonth, -2, 120, -2).addComponent(polloMonth, -2, 120, -2).addComponent(huevosMonth, -2, 120, -2).addComponent(frutaMonth, -2, 120, -2).addComponent(yogurthMonth, -2, 120, -2)).addGap(415, 415, 415)));
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addContainerGap().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(label34, -2, 30, -2).addComponent(label32, -2, 30, -2).addComponent(label31, -2, 30, -2).addComponent(label33, -2, 30, -2).addComponent(label35, -2, 30, -2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label12).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(yogurthType, -2, -1, -2).addComponent(yogurthDay, -2, -1, -2).addComponent(yogurthWeek, -2, -1, -2).addComponent(yogurthMonth, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label13).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(frutaType, -2, -1, -2).addComponent(frutaDay, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label14).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(verduraType, -2, -1, -2).addComponent(verduraDay, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(Yogurth_Label16).addComponent(tortillaType, -2, -1, -2)).addGap(18, 18, 18).addComponent(Yogurth_Label17, -2, 17, -2).addGap(18, 18, 18).addComponent(Yogurth_Label15).addGap(18, 18, 18).addComponent(jLabel17).addGap(18, 18, 18).addComponent(jLabel18).addGap(18, 18, 18).addComponent(jLabel19).addGap(18, 18, 18).addComponent(jLabel20).addGap(18, 18, 18).addComponent(jLabel21)).addGroup(jPanel7Layout.createSequentialGroup().addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel7Layout.createSequentialGroup().addComponent(panType, -2, -1, -2).addGap(6, 6, 6).addComponent(pastasType, -2, -1, -2)).addGroup(jPanel7Layout.createSequentialGroup().addComponent(tortillaDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(panDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(pastasDay, -2, -1, -2))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(jPanel7Layout.createSequentialGroup().addComponent(arrozType, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerealType, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(carnesType, -2, -1, -2).addGap(6, 6, 6).addComponent(polloType, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(huevosType, -2, -1, -2)).addGroup(jPanel7Layout.createSequentialGroup().addComponent(arrozDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerealDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(carnesDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(polloDay, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(huevosDay, -2, -1, -2)))))).addGroup(jPanel7Layout.createSequentialGroup().addComponent(frutaWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(verduraWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(tortillaWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(panWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(pastasWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(arrozWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerealWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(carnesWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(polloWeek, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(huevosWeek, -2, -1, -2)).addGroup(jPanel7Layout.createSequentialGroup().addComponent(frutaMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(verduraMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(tortillaMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(panMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(pastasMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(arrozMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cerealMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(carnesMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(polloMonth, -2, -1, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(huevosMonth, -2, -1, -2))).addContainerGap(14, 32767)));
        jTabbedPane3.addTab("Dieta", jPanel7);
        jTabbedPane1.addTab("Dieta", jTabbedPane3);
        addBtn.setText("A\361adir");
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jTabbedPane1, -2, 931, -2).addGap(0, 0, 32767)).addGroup(layout.createSequentialGroup().addComponent(jLabel5, -2, 200, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cancelBtn, -2, 200, -2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, 32767).addComponent(addBtn, -2, 200, -2).addGap(18, 18, 18).addComponent(jLabel6, -2, 200, -2)))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jTabbedPane1, -2, 552, -2).addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel5, -1, -1, 32767).addComponent(jLabel6, -1, -1, 32767).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(cancelBtn, -1, -1, 32767).addComponent(addBtn))).addContainerGap()));
        pack();
    }

    Message message;
    MainFrame main;
    private JLabel Yogurth_Label12;
    private JLabel Yogurth_Label13;
    private JLabel Yogurth_Label14;
    private JLabel Yogurth_Label15;
    private JLabel Yogurth_Label16;
    private JLabel Yogurth_Label17;
    private JLabel Yogurth_Label18;
    private JLabel Yogurth_Label19;
    private JLabel Yogurth_Label20;
    private JLabel Yogurth_Label21;
    private JLabel Yogurth_Label22;
    private JLabel Yogurth_Label23;
    private JTextArea actualAilmentTxt;
    private JTextArea actualTreatmentTxt;
    private JComboBox actvPhysBox;
    private JTextField actvPhysDurationTxt;
    private JTextPane actvPhysTxt;
    public JButton addBtn;
    private TextField adressTxt;
    private JLabel agua;
    private Checkbox alcoholismo_checkbox;
    private Checkbox alteracion_checkbox;
    private JTextField arrozDay;
    private JTextField arrozMonth;
    private JTextField arrozType;
    private JTextField arrozWeek;
    private JComboBox atcvPhysFrequenBox;
    private JTextField azucarDay;
    private JTextField azucarMonth;
    private JTextField azucarType;
    private JTextField azucarWeek;
    private ButtonGroup buttonGroup1;
    public JButton cancelBtn;
    private Checkbox cancer_checkbox;
    private Checkbox cansancio_checkbox;
    private Checkbox cardiopatia_checkbox;
    private JTextField carnesDay;
    private JTextField carnesMonth;
    private JTextField carnesType;
    private JTextField carnesWeek;
    private JTextField cerealDay;
    private JTextField cerealMonth;
    private JTextField cerealType;
    private JTextField cerealWeek;
    private JLabel colaciones;
    private JComboBox colationsBox;
    private JLabel comes;
    private JTextField comidaDay;
    private JTextField comidaMonth;
    private JTextField comidaType;
    private JTextField comidaWeek;
    private JTextArea complementsTxt;
    private JLabel cual_fisica;
    private Checkbox diabetes_checkbox;
    private Checkbox diarrea_checkbox;
    private Checkbox dislipidemias_checkbox;
    private JComboBox drinkFrequentyBox;
    private JTextField dulcesDay;
    private JTextField dulcesMonth;
    private JTextField dulcesType;
    private JTextField dulcesWeek;
    private JLabel duracion;
    private TextField dxTxt;
    private TextField eMailTxt;
    private JComboBox eatCountBox;
    private Checkbox enfhepaticas_checkbox;
    private Checkbox enfrenales_checkbox;
    private Checkbox enfrespiratorias_checkbox;
    private JLabel entre_comidas;
    private Checkbox estomacal_checkbox;
    private Checkbox estreF1imiento_checkbox;
    private JLabel fisica;
    private JLabel frecuencia;
    private JLabel frecuencia_fumas;
    private JTextField frutaDay;
    private JTextField frutaMonth;
    private JTextField frutaType;
    private JTextField frutaWeek;
    private Checkbox gastritis_checkbox;
    private Checkbox glucion_checkbox;
    private JTextField grasasDay;
    private JTextField grasasMonth;
    private JTextField grasasType;
    private JTextField grasasWeek;
    private JComboBox habitsYesNoBox01;
    private JComboBox habitsYesNoBox02;
    private JComboBox habitsYesNoBox03;
    private JLabel hambre;
    private TextField heightTxt;
    private TextField hipSizeTxt;
    private Checkbox hiper_checkbox;
    private JLabel horarios_comida;
    private JTextField huevosDay;
    private JTextField huevosMonth;
    private JTextField huevosType;
    private JTextField huevosWeek;
    private JTextPane hungryHourTxt;
    private Checkbox indigestion_checkbox;
    private JLabel jLabel1;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel7;
    private JPanel jPanel9;
    private JScrollPane jScrollPane12;
    private JScrollPane jScrollPane15;
    private JScrollPane jScrollPane16;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JScrollPane jScrollPane7;
    private JScrollPane jScrollPane8;
    private JTabbedPane jTabbedPane1;
    private JTabbedPane jTabbedPane3;
    private JTextField jamonDay;
    private JTextField jamonMonth;
    private JTextField jamonType;
    private JTextField jamonWeek;
    private Label label1;
    private Label label11;
    private Label label12;
    private Label label13;
    private Label label14;
    private Label label15;
    private Label label16;
    private Label label17;
    private Label label18;
    private Label label19;
    private Label label2;
    private Label label20;
    private Label label3;
    private Label label31;
    private Label label32;
    private Label label33;
    private Label label34;
    private Label label35;
    private Label label36;
    private Label label37;
    private Label label38;
    private Label label39;
    private Label label4;
    private Label label40;
    private Label label5;
    private Label label6;
    private Label label7;
    private JLabel label_fisica;
    private JLabel label_saltar;
    private JLabel label_saltar1;
    private JLabel lugar_comer;
    private Checkbox mareos_checkbox;
    private TextField nameTxt;
    private Checkbox nauseas_checkbox;
    private Checkbox obesidad_checkbox;
    private Checkbox otro_checkbox;
    private JTextField otrosDay;
    private JTextField otrosMonth;
    private JTextField otrosType;
    private JTextField otrosWeek;
    private JTextPane palceEatTxt;
    private JTextField panDay;
    private JTextField panMonth;
    private JTextField panType;
    private JTextField panWeek;
    private JTextField papasDay;
    private JTextField papasMonth;
    private JTextField papasType;
    private JTextField papasWeek;
    private JTextField pastasDay;
    private JTextField pastasMonth;
    private JTextField pastasType;
    private JTextField pastasWeek;
    private JTextField pescadoDay;
    private JTextField pescadoMonth;
    private JTextField pescadoType;
    private JTextField pescadoWeek;
    private TextField phone0Txt;
    private JTextField polloDay;
    private JTextField polloMonth;
    private JTextField polloType;
    private JTextField polloWeek;
    private JLabel prepara;
    private Checkbox profmasticacion_checkbox;
    private JTextField quesoDay;
    private JTextField quesoMonth;
    private JTextField quesoType;
    private JTextField quesoWeek;
    private JTextField refrescosDay;
    private JTextField refrescosMonth;
    private JTextField refrescosType;
    private JTextField refrescosWeek;
    private TextField riskTxt;
    private JTextField salchichaDay;
    private JTextField salchichaMonth;
    private JTextField salchichaType;
    private JTextField salchichaWeek;
    private JRadioButton sexFem;
    private JRadioButton sexMale;
    private JComboBox smokeFreqTxt;
    private Checkbox sobrepeso_checkbox;
    private JTextArea surgeriesTxt;
    private JTextField tortillaDay;
    private JTextField tortillaMonth;
    private JTextField tortillaType;
    private JTextField tortillaWeek;
    private JTextField verduraDay;
    private JTextField verduraMonth;
    private JTextField verduraType;
    private JTextField verduraWeek;
    private Checkbox vomito_checkbox;
    private TextField waistSizeTxt;
    private JTextPane watterTxt;
    private TextField weigthTxt;
    private JTextPane whoFoodsTxt;
    private TextField yearsTxt;
    private JTextField yogurthDay;
    private JTextField yogurthMonth;
    private JTextField yogurthType;
    private JTextField yogurthWeek;
}
